version: "3"

services:
  postgres:
    container_name: figma-for-jira-db
    image: postgres:14.8
    ports:
      - "${PG_FIGMA_FOR_JIRA_DB_PORT}:${PG_FIGMA_FOR_JIRA_DB_PORT}"
    environment:
      POSTGRES_USER: ${PG_FIGMA_FOR_JIRA_DB_ROLE}
      POSTGRES_PASSWORD: ${PG_FIGMA_FOR_JIRA_DB_PASSWORD}
      POSTGRES_DB: ${PG_FIGMA_FOR_JIRA_DB_SCHEMA}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
