version: "3"

services:
  postgres:
    image: postgres:14.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_FIGMA_FOR_JIRA_DB_ROLE}
      POSTGRES_PASSWORD: ${PG_FIGMA_FOR_JIRA_DB_PASSWORD}
      POSTGRES_DB: ${PG_FIGMA_FOR_JIRA_DB_SCHEMA}
