#!/usr/bin/env bash
set -eu

SQL="
CREATE USER $PG_FIGMA_FOR_JIRA_DB_ROLE WITH PASSWORD '$PG_FIGMA_FOR_JIRA_DB_PASSWORD';
CREATE DATABASE $PG_FIGMA_FOR_JIRA_DB_SCHEMA;
GRANT ALL PRIVILEGES ON DATABASE $PG_FIGMA_FOR_JIRA_DB_SCHEMA TO $PG_FIGMA_FOR_JIRA_DB_ROLE;
"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
$SQL
EOSQL
