on: [pull_request]
jobs:
  verify-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Check lint errors
        run: npm run lint

      - name: Check formatting errors
        run: npm run format:check

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:it:ci

      - name: Build Docker image
        run: docker build .
