on: [pull_request]
jobs:
  verify-app:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.8
        env:
          POSTGRES_USER: figma_for_jira_app
          POSTGRES_PASSWORD: password
          POSTGRES_DB: figma_for_jira
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Check type errors
        run: npm run build:check

      - name: Check lint errors
        run: npm run lint

      - name: Check formatting errors
        run: npm run format:check

      - name: Run Unit tests
        run: npm run test:unit

      - name: Run Integration tests
        run: npm run test:it

      - name: Build Docker image
        run: docker build .
