on: [push, pull_request]
jobs:
  verify-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Check type errors
        run: npm run build:clean

      - name: Check lint errors
        run: npm run lint

      - name: Check formatting errors
        run: npm run format:check

      - name: Tests
        run: npm test

      - name: Build Docker image
        run: docker build .
